# Base configs
baseurl: "https://albasdp.github.io"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"


# UI configs
title: "Alba Suarez de Puga"
subtitle: ""
author: "Template by Ram Patra"
bio: "I am a fashion crafter, a designer, a dressmaker and a dreamer"
publicise: ""
web_design: "AJ"
social_urls:
  linkedin: "https://www.linkedin.com/in/alba-su%C3%A1rez-de-puga-152b5020b/"
  facebook: "https://www.facebook.com/albasuarezdepuga/"
  instagram: "https://www.instagram.com/albasuarezdepuga/"
  